package vendorconsent

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"testing"
	"time"

	"github.com/prebid/go-gdpr/consentconstants"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

var debugLineNumber = 16

type disclosedVendorsExpectation struct {
	LineNumber               int             `json:"lineNumber"`
	ConsentString            string          `json:"consentString"`
	Version                  int             `json:"version"`
	Created                  string          `json:"created"`
	LastUpdated              string          `json:"lastUpdated"`
	CmpID                    int             `json:"cmpID"`
	CmpVersion               int             `json:"cmpVersion"`
	ConsentScreen            int             `json:"consentScreen"`
	ConsentLanguage          string          `json:"consentLanguage"`
	VendorListVersion        int             `json:"vendorListVersion"`
	TCFPolicyVersion         int             `json:"tcfPolicyVersion"`
	MaxVendorID              int             `json:"maxVendorID"`
	PurposeAllowed           map[string]bool `json:"purposeAllowed"`
	VendorConsent            map[string]bool `json:"vendorConsent"`
	OOBDisclosedVendorsMaxID *int            `json:"oobDisclosedVendorsMaxID"`
	DisclosedVendor          map[string]bool `json:"oobDisclosedVendor"`
}

func loadExpectations() ([]disclosedVendorsExpectation, map[int]*disclosedVendorsExpectation, error) {
	// this file is generated by taking the values github.com/LiveRamp/iabconsent returns
	// (it allocates too much memory for our purposes, so we can't use it directly)
	expectationsFile := filepath.Join("expectations.json")
	data, err := os.ReadFile(expectationsFile)
	if err != nil {
		return nil, nil, fmt.Errorf("failed to read expectations.json: %w", err)
	}

	var expectations []disclosedVendorsExpectation
	if err := json.Unmarshal(data, &expectations); err != nil {
		return nil, nil, fmt.Errorf("failed to parse expectations.json: %w", err)
	}

	expectationsMap := make(map[int]*disclosedVendorsExpectation)
	for i := range expectations {
		exp := &expectations[i]
		expectationsMap[exp.LineNumber] = exp
	}

	return expectations, expectationsMap, nil
}

func compareConsentWithExpected(t *testing.T, consentString string, expected *disclosedVendorsExpectation) {
	t.Helper()

	ourParsed, err := ParseString(consentString)
	require.NoError(t, err, "ParseString should succeed")

	assert.Equal(t, expected.Version, int(ourParsed.Version()), "Version mismatch")

	expectedCreated, err := time.Parse(time.RFC3339, expected.Created)
	require.NoError(t, err, "failed to parse expected Created time")
	assert.True(t, expectedCreated.Equal(ourParsed.Created()), "Created mismatch: expected=%v, got=%v", expectedCreated, ourParsed.Created())

	expectedLastUpdated, err := time.Parse(time.RFC3339, expected.LastUpdated)
	require.NoError(t, err, "failed to parse expected LastUpdated time")
	assert.True(t, expectedLastUpdated.Equal(ourParsed.LastUpdated()), "LastUpdated mismatch: expected=%v, got=%v", expectedLastUpdated, ourParsed.LastUpdated())

	assert.Equal(t, expected.CmpID, int(ourParsed.CmpID()), "CmpID mismatch")
	assert.Equal(t, expected.CmpVersion, int(ourParsed.CmpVersion()), "CmpVersion mismatch")
	assert.Equal(t, expected.ConsentScreen, int(ourParsed.ConsentScreen()), "ConsentScreen mismatch")
	assert.Equal(t, expected.ConsentLanguage, ourParsed.ConsentLanguage(), "ConsentLanguage mismatch")
	assert.Equal(t, expected.VendorListVersion, int(ourParsed.VendorListVersion()), "VendorListVersion mismatch")
	assert.Equal(t, expected.TCFPolicyVersion, int(ourParsed.TCFPolicyVersion()), "TCFPolicyVersion mismatch")
	assert.Equal(t, expected.MaxVendorID, int(ourParsed.MaxVendorID()), "MaxVendorID mismatch")

	for purposeID := consentconstants.Purpose(1); purposeID <= 24; purposeID++ {
		purposeKey := fmt.Sprintf("%d", purposeID)
		expectedAllowed, ok := expected.PurposeAllowed[purposeKey]
		require.True(t, ok, "PurposeAllowed(%d) not found in expectations", purposeID)
		assert.Equal(t, expectedAllowed, ourParsed.PurposeAllowed(purposeID), "PurposeAllowed(%d) mismatch", purposeID)
	}

	ourMaxVendorID := ourParsed.MaxVendorID()
	for vendorID := uint16(1); vendorID <= ourMaxVendorID; vendorID++ {
		vendorKey := fmt.Sprintf("%d", vendorID)
		expectedConsent, ok := expected.VendorConsent[vendorKey]
		require.True(t, ok, "VendorConsent(%d) not found in expectations", vendorID)
		assert.Equal(t, expectedConsent, ourParsed.VendorConsent(vendorID), "VendorConsent(%d) mismatch", vendorID)
	}

	if expected.OOBDisclosedVendorsMaxID == nil {
		assert.Equal(t, uint16(0), ourParsed.OOBDisclosedVendorsMaxID(), "expected has no disclosed vendors, but ours has max ID")
	} else {
		assert.Equal(t, uint16(*expected.OOBDisclosedVendorsMaxID), ourParsed.OOBDisclosedVendorsMaxID(), "OOBDisclosedVendors MaxVendorID mismatch")

		disclosedMaxID := uint16(*expected.OOBDisclosedVendorsMaxID)
		for vendorID := uint16(1); vendorID <= disclosedMaxID; vendorID++ {
			vendorKey := fmt.Sprintf("%d", vendorID)
			expectedDisclosed, ok := expected.DisclosedVendor[vendorKey]
			require.True(t, ok, "DisclosedVendor(%d) not found in expectations", vendorID)
			assert.Equal(t, expectedDisclosed, ourParsed.DisclosedVendor(vendorID), "DisclosedVendor(%d) mismatch", vendorID)
		}
	}
}

func TestConsentsFile_CompareWithIABConsent(t *testing.T) {
	expectations, _, err := loadExpectations()
	require.NoError(t, err, "Failed to load expectations")

	passed := 0
	failed := 0

	for i := range expectations {
		expected := &expectations[i]
		t.Run(fmt.Sprintf("line_%d", expected.LineNumber), func(t *testing.T) {
			compareConsentWithExpected(t, expected.ConsentString, expected)
			if t.Failed() {
				failed++
			} else {
				passed++
			}
		})
	}

	t.Logf("Processed %d consent strings: %d passed, %d failed", len(expectations), passed, failed)
}
